// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcHcZnQdIYLYInZfQBUT2nEU05tFzWKbc',
    appId: '1:318497541894:web:7201736e5b186513881887',
    messagingSenderId: '318497541894',
    projectId: 'laundry-868ba',
    authDomain: 'laundry-868ba.firebaseapp.com',
    storageBucket: 'laundry-868ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-NJmoCKg_coJiyP0ttflhZUZTTRstfI',
    appId: '1:318497541894:android:48ccdca13c98269f881887',
    messagingSenderId: '318497541894',
    projectId: 'laundry-868ba',
    storageBucket: 'laundry-868ba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcHcZnQdIYLYInZfQBUT2nEU05tFzWKbc',
    appId: '1:318497541894:web:b1caa9ea0055025b881887',
    messagingSenderId: '318497541894',
    projectId: 'laundry-868ba',
    authDomain: 'laundry-868ba.firebaseapp.com',
    storageBucket: 'laundry-868ba.firebasestorage.app',
  );
}
